// packages/adapter-web/src/provider.tsx
import {
  createContext,
  useContext,
  useMemo,
  useId,
  type ComponentType,
  type ReactElement,
  type ReactNode,
} from "react";
import type { ResolvedTheme, ComponentRole } from "@polymorph/spec";
import { createBridge, type ThemeBridge } from "./theme-bridge.js";
import { toCssVariablesString } from "./css-vars.js";
import { resolveSlot, type SlotComponents, type SlotName } from "./slots.js";
import { resolveComponent, type ComponentRegistry } from "./component-map.js";

export interface ThemeContextValue {
  theme: ResolvedTheme;
  bridge: ThemeBridge;
  slots: SlotComponents;
  components: ComponentRegistry;
  /** The CSS class the provider applies to its wrapper (useful for portals). */
  scope: string;
}

const ThemeContext = createContext<ThemeContextValue | null>(null);

export interface ThemeProviderProps {
  /** A resolved theme (from @polymorph/core or a loader handle). */
  theme: ResolvedTheme;
  /** Host render-slot overrides. */
  slots?: SlotComponents;
  /** Host role→component mappings. */
  components?: ComponentRegistry;
  /** Custom scope class. Default: a unique per-instance class. */
  scope?: string;
  children?: ReactNode;
}

/**
 * Injects the resolved theme's CSS variables scoped to a wrapper element and provides context
 * with the bridge, slot registry, and component registry. Switching `theme` updates the injected
 * stylesheet — children don't remount, and styles cascade through `var(--…)` references.
 */
export function ThemeProvider(props: ThemeProviderProps): ReactElement {
  const { theme, slots, components, scope, children } = props;
  const generated = useId().replace(/:/g, "");
  const cls = scope ?? `pm-theme-${generated}`;
  const css = useMemo(() => toCssVariablesString(theme, `.${cls}`), [theme, cls]);
  const value = useMemo<ThemeContextValue>(
    () => ({
      theme,
      bridge: createBridge(theme),
      slots: slots ?? {},
      components: components ?? {},
      scope: cls,
    }),
    [theme, slots, components, cls],
  );
  return (
    <ThemeContext.Provider value={value}>
      <style data-polymorph-theme={cls}>{css}</style>
      <div className={cls}>{children}</div>
    </ThemeContext.Provider>
  );
}

export function useTheme(): ThemeContextValue {
  const v = useContext(ThemeContext);
  if (!v) throw new Error("useTheme must be used within a <ThemeProvider>");
  return v;
}
export const useThemeBridge = (): ThemeBridge => useTheme().bridge;
export const useResolvedTheme = (): ResolvedTheme => useTheme().theme;

export function useSlot<P>(name: SlotName, fallback: ComponentType<P>): ComponentType<P> {
  return resolveSlot(useTheme().slots, name, fallback);
}
export function useThemedComponent<P>(role: ComponentRole, fallback: ComponentType<P>): ComponentType<P> {
  return resolveComponent(useTheme().components, role, fallback);
}

// packages/adapter-web-solid/src/provider.ts
import { createContext, createMemo, createUniqueId, type Component, type JSX } from "solid-js";
import h from "solid-js/h";
import type { ResolvedTheme } from "@polymorph/spec";
import { createBridge, toCssVariablesString } from "@polymorph/adapter-web";
import type { ComponentRegistry, SlotComponents, ThemeContextValue } from "./types.js";

/** The Solid context carrying the theme + bridge + slot/component registries to descendants. */
export const ThemeContext = createContext<ThemeContextValue | null>(null);

export interface ThemeProviderProps {
  theme: ResolvedTheme;
  slots?: SlotComponents;
  components?: ComponentRegistry;
  /** Override the auto-generated wrapper class. */
  scope?: string;
  children?: JSX.Element;
}

/**
 * Injects a scoped `<style>` block with the resolved theme's CSS variables and provides context
 * (theme / bridge / slots / components / scope) to descendants via Solid's `createContext`.
 * Switching the `theme` prop updates the variables (fine-grained reactivity — descendants don't
 * re-render unless they read theme-dependent values directly).
 */
export const ThemeProvider: Component<ThemeProviderProps> = (props) => {
  const uid = createUniqueId();
  const scope = createMemo(() => props.scope || `pm-theme-${uid}`);
  const bridge = createMemo(() => createBridge(props.theme));
  const css = createMemo(() => toCssVariablesString(props.theme, `.${scope()}`));

  // Getter-backed context: reads stay reactive on prop changes (Solid tracks the access).
  const ctx: ThemeContextValue = {
    get theme() {
      return props.theme;
    },
    get bridge() {
      return bridge();
    },
    get slots() {
      return props.slots ?? {};
    },
    get components() {
      return props.components ?? {};
    },
    get scope() {
      return scope();
    },
  };

  // `solid-js/h` returns a callable that resolves to JSX.Element under Solid's reactivity;
  // cast at the boundary so this conforms to `Component<P>`. Runtime is unaffected.
  return h(ThemeContext.Provider, {
    value: ctx,
    get children() {
      return h("div", { class: scope() }, [
        h("style", { "data-polymorph-theme": scope() }, css()),
        props.children,
      ]);
    },
  }) as unknown as JSX.Element;
};
